apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 113296432577.dkr.ecr.us-east-1.amazonaws.com/movie-picture-frontend:d416a3dcb1049baeae8df6034612605040e4d043
          ports:
            - containerPort: 3000
