apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 113296432577.dkr.ecr.us-east-1.amazonaws.com/movie-picture-backend:d416a3dcb1049baeae8df6034612605040e4d043
          ports:
            - containerPort: 5000
